<?php
/**
 * Created by PhpStorm.
 * User: USER
 * Date: 16-May-19
 * Time: 3:14 PM
 */

namespace backend\modules\baocao\models\doanhthu\search;

use backend\modules\baocao\models\doanhthu\BaoCaoDonHangModel;
use yii\base\Model;
use yii\data\ActiveDataProvider;

class BaoCaoDonHangModelSearch extends BaoCaoDonHangModel
{
    public $button;
    public $from;
    public $to;
    public $type_search_date = 'date';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['co_so'], 'integer'],
            [['order_code'], 'safe'],
            [['button', 'from', 'to', 'type_search_date'], 'string'],
        ];
    }

    public function scenarios()
    {
        return Model::scenarios();
    }


    public function search($params)
    {
        $query = BaoCaoDonHangModel::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'defaultPageSize' => 10
            ],
            'sort' => ['defaultOrder' => ['id' => SORT_DESC]]
        ]);

        $this->load($params);

        if (!$this->validate()) {
            return $dataProvider;
        }
        $query->andFilterWhere([
            'co_so' => $this->co_so,
        ]);


        if (isset($this->type_search_date)) {
            if ($this->type_search_date == 'date') {
                if (isset($this->from) && $this->from != null) {
                    $from = strtotime($this->from);
                    $to = strtotime($this->from) + 86399;
                    $query->andFilterWhere(['>', 'created_at', $from]);
                    $query->andFilterWhere(['<', 'created_at', $to]);
                }
            } else {
                if (isset($this->from) && isset($this->to) && $this->from != null & $this->to != null) {
                    $from = strtotime($this->from);
                    $to = strtotime($this->to) + 86399;
                    $query->andFilterWhere(['>', 'created_at', $from]);
                    $query->andFilterWhere(['<', 'created_at', $to]);
                }
            }
        }

        return $dataProvider;
    }
}
