<?php
/**
 * Created by PhpStorm.
 * User: abc
 * Date: 3/26/2020
 * Time: 11:04 AM
 */

namespace backend\modules\chi\models;


use yii\db\ActiveRecord;

class ThuchiTieuChiModel extends ActiveRecord
{
    public static function tableName()
    {
        return 'thuchi_tieu_chi';
    }

    public static function getById($id)
    {
        $cache = \Yii::$app->cache;
        $key = 'thuchi-tieu-chi-get-by-id-' . $id;
        $data = $cache->get($key);
        if ($data === false) {
            $data = self::find()->where(['id' => $id])->one();
            $cache->set($key, $data);
        }
        return $data;
    }

    public function beforeSave($insert)
    {
        $cache = \Yii::$app->cache;
        $id = $this->primaryKey;
        $key = 'thuchi-tieu-chi-get-by-id-' . $id;
        $cache->delete($key);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        $cache = \Yii::$app->cache;
        $id = $this->primaryKey;
        $key = 'thuchi-tieu-chi-get-by-id-' . $id;
        $cache->delete($key);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


}