<?php
/**
 * Created by PhpStorm.
 * User: abc
 * Date: 3/10/2020
 * Time: 3:53 PM
 */

namespace backend\modules\chi\assets;


use backend\assets\AppAsset;
use backend\assets\BootstrapSliderAsset;
use unclead\multipleinput\assets\MultipleInputAsset;
use yii\bootstrap\BootstrapPluginAsset;
use yii\web\AssetBundle;
use yii\web\View;

class DexuatchiAssets extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $request = \Yii::$app->controller->action->id;
        switch ($request) {
            case 'update':
                $this->js[] = 'modules/dexuatchi/js/dexuatchi_update_create.js';
                $this->js[] = 'modules/dexuatchi/js/dexuatchi_form.js';
                break;
            case 'create':
                $this->js[] = 'modules/dexuatchi/js/dexuatchi_update_create.js';
                $this->js[] = 'modules/dexuatchi/js/dexuatchi_form.js';
                break;
            case 'view':
                $this->js[] = 'modules/dexuatchi/js/dexuatchi_view.js';
                break;
            default:
                $this->js[] = 'modules/dexuatchi/js/dexuatchi_index.js';
                break;

        }
        $this->css = [
            '/modules/dexuatchi/css/dexuatchi.css'
        ];
    }


    public $jsOptions = ['position' => View::POS_END];


    public $cssOptions;

    public $depends = [
        AppAsset::class,
        MultipleInputAsset::class,
        BootstrapPluginAsset::class,
        BootstrapSliderAsset::class
    ];
}



