<?php

namespace backend\modules\clinic\models\search;

use backend\models\CustomerModel;
use backend\modules\clinic\models\Clinic;
use backend\modules\clinic\models\DonHangBaoHanh;
use backend\modules\user\models\User;
use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;

/**
 * Dep365CustomerOnlineSearch represents the model behind the search form of `backend\modules\customer\models\Dep365CustomerOnline`.
 */
class DonHangBaoHanhSearch extends DonHangBaoHanh
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
        ];
    }

    public function scenarios()
    {
        return Model::scenarios();
    }


    public function search($listDonHangSearch)
    {

        $query = DonHangBaoHanh::find()->where(['phong_kham_don_hang_id' => $listDonHangSearch]);

//        $this->load($params);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' => ['defaultOrder' => ['id' => SORT_DESC]]
        ]);

        if (!$this->validate()) {
            return $dataProvider;
        }

        return $dataProvider;
    }
}
