<?php

namespace backend\modules\directsale\models\search;

use backend\components\CustomerModel;
use backend\modules\clinic\models\Clinic;
use backend\modules\user\models\User;
use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use backend\modules\directsale\models\DirectSaleModel;
use backend\modules\customer\models\Dep365CustomerOnlineCome;
use backend\modules\clinic\models\PhongKhamLichDieuTri;

/**
 * DirectSaleSearch represents the model behind the search form of `backend\modules\directsale\models\DirectSaleModel`.
 */
class DirectSaleSearch extends DirectSaleModel
{
    const DA_DEN = 1;

    public $button = '';
    public $from;
    public $to;
    public $keyword;
    public $come_time_from;
    public $come_time_to;
    public $customer_come_time_to;
    public $type_search_date = 'date';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['district', 'co_so', 'permission_user'], 'integer'],
            [['name', 'phone', 'customer_code', 'sex', 'birthday', 'time_lichhen', 'full_name'], 'safe'],
            [['button', 'from', 'to', 'keyword', 'come_time_from', 'come_time_to', 'customer_come_time_to', 'type_search_date'], 'safe'],
        ];
    }

    public function scenarios()
    {
        return Model::scenarios();
    }


    public function search($params)
    {
        $user = new User();
        $roleUser = $user->getRoleName(\Yii::$app->user->id);

        $query = Clinic::find()->where([CustomerModel::tableName() . '.status' => Clinic::STATUS_DH, CustomerModel::tableName() . '.dat_hen' => self::DA_DEN]);

        if ($roleUser == User::USER_DIRECT_SALE) {
            $query->andFilterWhere([CustomerModel::tableName() . '.directsale' => \Yii::$app->user->id]);
        }

        if ($roleUser == User::USER_BAC_SI) {
            $query->joinWith(['phongKhamLichDieuTriHasOne', 'customerOnlineComeHasOne']);
            $query->andFilterWhere([PhongKhamLichDieuTri::tableName() . '.ekip' => \Yii::$app->user->id]);
            $query->andFilterWhere([Dep365CustomerOnlineCome::tableName() . '.accept' => 1]); // khach dong y, khach vang lai dong y
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'defaultPageSize' => 10
            ],
            'sort' => ['defaultOrder' => ['id' => SORT_DESC]]
        ]);

        $this->load($params);

        if ($this->button == '') {
            $this->come_time_from = date('d-m-Y');
            $this->come_time_to = date('d-m-Y');
        }

        if ($this->button == '2' && $roleUser == User::USER_DIRECT_SALE) {
            $rowUser = User::findIdentity(\Yii::$app->user->id);
            $this->co_so = $rowUser->permission_coso;
        }

        $query->joinWith(['provinceHasOne']);

        if (!$this->validate()) {
            return $dataProvider;
        }

        $query->andFilterWhere([
            'co_so' => $this->co_so,
//            'phone' => $this->phone,
        ]);

        /* Search name, phone, code */
        if (isset($this->keyword) && $this->keyword != null) {
            $this->keyword = trim($this->keyword);
            $this->keyword = preg_replace('/\s+/', ' ', $this->keyword);
            $query->andFilterWhere(['or',
                ['like', CustomerModel::tableName() . '.full_name', $this->keyword],
                ['like', CustomerModel::tableName() . '.forename', $this->keyword],
                ['like', CustomerModel::tableName() . '.name', $this->keyword],
                ['like', CustomerModel::tableName() . '.phone', $this->keyword],
                ['like', CustomerModel::tableName() . '.customer_code', $this->keyword],
            ]);
        }

        /* Search lịch hẹn */
        if (isset($this->type_search_date)) {
            if ($this->type_search_date == 'date') {
                if (isset($this->come_time_from) && $this->come_time_from != null) {
                    $from = strtotime($this->come_time_from);
                    $to = strtotime($this->come_time_from) + 86399;
                    $query->andFilterWhere(['>', CustomerModel::tableName() . '.customer_come', $from]);
                    $query->andFilterWhere(['<', CustomerModel::tableName() . '.customer_come', $to]);
                }
            } else {
                if (isset($this->come_time_from) && isset($this->come_time_to) &&
                    $this->come_time_from != null && $this->come_time_to != null) {
                    $from = strtotime($this->come_time_from);
                    $to = strtotime($this->come_time_to) + 86399;
                    $query->andFilterWhere(['>', CustomerModel::tableName() . '.customer_come', $from]);
                    $query->andFilterWhere(['<', CustomerModel::tableName() . '.customer_come', $to]);
                }
            }
        }

        if (isset($this->co_so) && $this->co_so != null) {
            $query->andFilterWhere([CustomerModel::tableName() . '.co_so' => $this->co_so]);
        }

        if (isset($this->customer_come_time_to) && $this->customer_come_time_to != null) {
            $query->andFilterWhere([CustomerModel::tableName() . '.customer_come_time_to' => $this->customer_come_time_to]);
        }

//        echo $query->createCommand()->getRawSql(); die;

        return $dataProvider;
    }
}
