<?php

namespace backend\widgets;

use backend\models\Dep365CustomerOnlineRemindCall;
use backend\modules\customer\models\CustomerOnlineRemindCall;
use backend\modules\directsale\models\DirectSaleRemindCall;
use backend\modules\log\models\CallLog;
use backend\modules\user\models\User;
use yii\base\Widget;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;

class AlertWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $user = new User();
        $roleName = $user->getRoleName(\Yii::$app->user->id);
        $module = \Yii::$app->controller->module->id;
        $controller = \Yii::$app->controller->id;
        $action = \Yii::$app->controller->action->id;
        $edit = \Yii::$app->request->get('edit');
        /*
         * TƯ VẤN ONLINE + ĐANG Ở TRANG NHẮC LỊCH ONLINE => NULL
         * DIRECT SALE + ĐANG Ở TRANG NHẮC LỊCH DIRECT SALE => NULL
         * */
        if ((!in_array($roleName, [
                /*User::USER_DIRECT_SALE,
                User::USER_MANAGER_DIRECT_SALE,*/
                User::USER_NHANVIEN_ONLINE,
                User::USER_MANAGER_ONLINE
            ])) /*|| (in_array($roleName, [
                    User::USER_DIRECT_SALE,
                    User::USER_MANAGER_DIRECT_SALE
                ]) && $module == 'directsale' && $controller == 'direct-sale-remind-call')*/ || (in_array($roleName, [
                    User::USER_NHANVIEN_ONLINE,
                    User::USER_MANAGER_ONLINE
                ]) && $module == 'customer' && ($controller == 'customer-online-remind-call' || ($controller == 'customer-online' && $action == 'index' && $edit == 'true')))) {
            return null;
        }
        if (in_array($roleName, [
            User::USER_DIRECT_SALE,
            User::USER_MANAGER_DIRECT_SALE
        ])) {
            return null;
            /*
             * DIRECT SALE CHỈ HIỆN SỐ LƯỢNG KHÁCH CẦN CHĂM SÓC CỦA DIRECT SALE ĐÓ
             * MANAGER DIRECT SALE HIỆN SỐ LƯỢNG TẤT CẢ KHÁCH CẦN CHĂM SÓC CỦA DIRECT SALE
             * */
            /*$query = DirectSaleRemindCall::find()->where(['type' => DirectSaleRemindCall::TYPE_DIRECT_SALE, 'remind_call_time' => strtotime(date('d-m-Y'))])->published();
            if ($roleName == User::USER_DIRECT_SALE) $query->andWhere([CustomerOnlineRemindCall::tableName() . '.permission_user' => \Yii::$app->user->id]);
            $url = Url::toRoute(['/directsale/direct-sale-remind-call']);*/
        } else {
            /*
             * NHAN VIEN ONLINE CHỈ HIỆN SỐ LƯỢNG KHÁCH CẦN CHĂM SÓC CỦA NHAN VIEN ONLINE ĐÓ
             * MANAGER ONLINE HIỆN SỐ LƯỢNG TẤT CẢ KHÁCH CẦN CHĂM SÓC CỦA NHAN VIEN ONLINE
             * */
            $query = CustomerOnlineRemindCall::find()
                ->select(
                /*CustomerOnlineRemindCall::tableName() . '.id, ' .
                CustomerOnlineRemindCall::tableName() . '.customer_id, ' .
                CustomerOnlineRemindCall::tableName() . '.status, ' .
                CustomerOnlineRemindCall::tableName() . '.dat_hen, ' .
                CustomerOnlineRemindCall::tableName() . '.status_fail, ' .
                CustomerOnlineRemindCall::tableName() . '.dat_hen_fail, ' .
                CustomerOnlineRemindCall::tableName() . '.type, ' .*/
                    CustomerOnlineRemindCall::tableName() . '.*, (SELECT count(*) FROM call_log WHERE call_log.nhac_lich_id=dep365_customer_online_remind_call.id AND call_time>0 AND call_log.created_at>dep365_customer_online_remind_call.updated_at) AS take_care'
                )
                /*->groupBy([
                    CustomerOnlineRemindCall::tableName() . '.id',
                    CustomerOnlineRemindCall::tableName() . '.customer_id',
                    CustomerOnlineRemindCall::tableName() . '.status',
                    CustomerOnlineRemindCall::tableName() . '.dat_hen',
                    CustomerOnlineRemindCall::tableName() . '.status_fail',
                    CustomerOnlineRemindCall::tableName() . '.dat_hen_fail',
                    CustomerOnlineRemindCall::tableName() . '.type',
                ])*/
                ->joinWith(['customerOnlineFailStatus', 'customerOnlineFailDatHen', 'customerOnlineHasOne'])
                ->where([
                    'type' => CustomerOnlineRemindCall::TYPE_CUSTOMER_ONLINE,
//                    'remind_call_time' => strtotime(date('d-m-Y'))
                ])
                ->andWhere(['BETWEEN', "remind_call_time", strtotime(date('d-m-Y')), strtotime(date('d-m-Y')) + 86399])
                ->published();
            if ($roleName == User::USER_NHANVIEN_ONLINE) {
                $query->andWhere([CustomerOnlineRemindCall::tableName() . '.permission_user' => \Yii::$app->user->id]);
            }
            $url = Url::toRoute(['/customer/customer-online-remind-call']);
        }
        if ($query->count() <= 0) {
            return null;
        }


        $cache = \Yii::$app->cache;
        $key = 'alert-widget-onlines-' . \Yii::$app->user->id;

        $nhaclich = $cache->get($key);

        if ($nhaclich == false) {
            $nhaclich = new ActiveDataProvider([
                'query' => $query,
                'sort' => false,
            ]);
            $cache->set($key, $nhaclich, 600);
        }

        return $this->render('alertWidget', [
            'url' => $url,
            'nhaclich' => $nhaclich,
            'roleName' => $roleName
        ]);
    }
}
