<?php

namespace backend\widgets;

use backend\modules\chi\models\Comment;
use yii\base\Widget;

class ChatWidget extends Widget
{
    public $listComment = [];
    public $formComment = null;
    public $model = null;
    public $commentTable = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('chatWidget', [
            'listComment' => $this->listComment,
            'formComment' => $this->formComment,
            'model' => $this->model,
            'commentTable' => $this->commentTable
        ]);
    }
}