<?php

namespace backend\widgets;

use yii\base\Widget;

class FileWidget extends Widget
{
    public $id;

    public $idModal = '';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('fileWidget', [
            'id' => $this->id,
            'idModal' => $this->idModal,
        ]);
    }
}
