<?php

namespace backend\widgets;

use yii\base\Widget;

class FooterWidget extends Widget
{
    public $contact;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
//        return $this->render('footerWidget', [
//
//        ]);
    }
}
