<?php

namespace backend\widgets;

use backend\modules\booking\models\CustomerOnlineBooking;
use backend\modules\clinic\models\PhongKhamDonHangWThanhToan;
use backend\modules\customer\models\AffiliateCustomerContact;
use backend\modules\customer\models\CustomerOnlineRemindCall;
use backend\modules\directsale\models\DirectSaleRemindCall;
use backend\modules\support\models\SupportCatagory;
use yii\base\Widget;

class LeftWidget extends Widget
{
    public $contact;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $supportCatagories = SupportCatagory::getCatagory();
        $totalBooking = CustomerOnlineBooking::getTotalCustomerBooking(CustomerOnlineBooking::STATUS_DISABLED);
        $affiliateCustomerContact = AffiliateCustomerContact::getTotalAffiliateCustomerContact();
        $customerRemind = CustomerOnlineRemindCall::getTotalRemindToday();
        $directsaleRemind = DirectSaleRemindCall::getTotalRemindToday();
        $returnDeposit = PhongKhamDonHangWThanhToan::getCountReturnDeposit();

        return $this->render('leftWidget', [
            'supportCatagories' => $supportCatagories,
            'totalBooking' => $totalBooking,
            'affiliateCustomerContact' => $affiliateCustomerContact,
            'customerRemind' => $customerRemind,
            'directsaleRemind' => $directsaleRemind,
            'returnDeposit' => $returnDeposit,
        ]);
    }
}
