<?php

namespace backend\modules\customer\models;

use backend\modules\customer\models\query\Dep365CustomerOnlineNguonQuery;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\SluggableBehavior;
use yii\db\ActiveRecord;
use common\models\UserProfile;

/**
 * This is the model class for table "dep365_customer_online_nguon".
 *
 * @property int $id
 * @property string $name
 * @property string $slug
 * @property string $mota
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property int $created_by
 * @property int $updated_by
 */
class Dep365CustomerOnlineNguon extends \yii\db\ActiveRecord
{
    const STATUS_PUBLISHED = 1;
    const STATUS_DRAFF = 0;

    const IS_NGUON_LE_TAN = 2;
    const IS_NGUON_TV_ONLINE = 1;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'dep365_customer_online_nguon';
    }

    public static function find()
    {
        return new Dep365CustomerOnlineNguonQuery(get_called_class());
    }

    public function behaviors()
    {
        return [
            'slug' => [
                'class' => SluggableBehavior::class,
                'attribute' => 'name',
                'slugAttribute' => 'slug',
                'immutable' => true, //only create 1
                'ensureUnique' => true, //
            ],
            [
                'class' => BlameableBehavior::class,
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'preserveNonEmptyValues' => true,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'slug', 'agency_id'], 'required'],
            [['mota'], 'string'],
            [['status', 'created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
            [['name', 'slug'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'name' => Yii::t('backend', 'Nguồn khách hàng'),
            'slug' => Yii::t('backend', 'Slug'),
            'mota' => Yii::t('backend', 'Mota'),
            'agency_id' => 'Agency',
            'status' => Yii::t('backend', 'Status'),
            'created_at' => Yii::t('backend', 'Created At'),
            'updated_at' => Yii::t('backend', 'Updated At'),
            'created_by' => Yii::t('backend', 'Created By'),
            'updated_by' => Yii::t('backend', 'Updated By'),
        ];
    }

    public function afterFind()
    {
        $this->agency_id = json_decode($this->agency_id);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        $id = $this->primaryKey;
        $cache = Yii::$app->cache;
        $key = 'redis-get-nguon-customer-online-' . $id;
        $cache->delete($key);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $id = $this->primaryKey;
        $cache = Yii::$app->cache;
        $key = 'redis-get-nguon-customer-online-' . $id;
        $cache->delete($key);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /*
     * Trả về Nguồn Online thuộc những agency nào
     */
    public static function getAgencyForNguonOnline($idAgency, $isCreate = null): array
    {
        $query = self::find()->published();
        $query->andWhere('agency_id like \'%"' . $idAgency . '"%\'');
//        if ($isCreate == null)
//            $query->andWhere(['is_create' => self::IS_NGUON_TV_ONLINE]);
        return $query->all();
    }

    /*
     * Lấy toàn bộ Agency
     */
    public static function getNguonCustomerOnline($isCreate = null)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-get-nguon-customer-online';
        $data = $cache->get($key);
        if ($data === false) {
            $query = self::find();
//            if ($isCreate == null)
//                $query->where(['is_create' => self::IS_NGUON_TV_ONLINE]);
            $data = $query->published()->all();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getNguonCustomerOnlineOne($id)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-get-nguon-customer-online-' . $id;
        $data = $cache->get($key);
        if ($data === false) {
            $query = self::find()->where(['id' => $id]);
            $data = $query->published()->one();
            $cache->set($key, $data, 86400 * 30);
        }
        return $data;
    }

    public function getUserCreatedBy($id)
    {
        if ($id == null) {
            $id = 2;
        }
        $user = UserProfile::find()->where(['user_id' => $id])->one();
        return $user;
    }

    public function getUserUpdatedBy($id)
    {
        if ($id == null) {
            $id = 2;
        }
        $user = UserProfile::find()->where(['user_id' => $id])->one();
        return $user;
    }
}
