<?php

namespace backend\modules\clinic\controllers;

use backend\modules\clinic\components\HinhCustomer;
use backend\modules\clinic\models\Clinic;
use backend\modules\clinic\models\CustomerImages;
use backend\modules\clinic\models\form\FormChupHinh;
use backend\modules\clinic\models\form\FormAvatarCustomer;
use backend\modules\clinic\models\PhongKhamChupBanhMoi;
use backend\modules\clinic\models\PhongKhamChupCui;
use backend\modules\clinic\models\PhongKhamChupFinal;
use backend\modules\clinic\models\PhongKhamDentalForm;
use backend\modules\clinic\models\PhongKhamHinhFinal;
use backend\modules\clinic\models\PhongKhamHinhTknc;
use backend\modules\clinic\models\PhongKhamUomRang1;
use backend\modules\clinic\models\PhongKhamUomRang2;
use backend\modules\customer\models\Dep365CustomerOnlineImport;
use common\helpers\MyHelper;
use GuzzleHttp\Client;
use Yii;
use backend\modules\clinic\models\PhongKhamChupHinh;
use backend\components\GapiComponent;
use yii\db\Transaction;
use yii\helpers\Url;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * ChupHinhController implements the CRUD actions for PhongKhamChupHinh model.
 */
class ChupHinhController extends HinhCustomer
{
    const FOLDER = 'chup-hinh';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        ini_set('memory_limit', '-1');
        set_time_limit(600);
    }

    public function actionUpload($id)
    {
        $customer = Clinic::find()->where(['id' => $id])->one();
        if ($customer === null) {
            Yii::$app->session->setFlash('alert', [
                'class' => 'alert-warning',
                'body' => 'Không tìm thấy dữ liệu'
            ]);
            return $this->redirect(Url::toRoute('index'));
        }
        if ($customer->full_name == null) {
            Yii::$app->session->setFlash('alert', [
                'body' => 'Vui lòng cập nhật Họ và Tên đầy đủ của khách hàng!',
                'class' => 'alert-warning'
            ]);
            return $this->redirect(Url::toRoute('index'));
        }
        $formAvatar = new FormAvatarCustomer();
        $formAvatar->fileImage = $customer->avatar;
        $formAvatar->id = $customer->primaryKey;
        $formChupHinh = new PhongKhamChupHinh();
        $formChupBanhMoi = new PhongKhamChupBanhMoi();
        $formChupCui = new PhongKhamChupCui();
        $formChupFinal = new PhongKhamChupFinal();
        $formHinhTknc = new PhongKhamHinhTknc();
        $formUomRang1 = new PhongKhamUomRang1();
        $formUomRang2 = new PhongKhamUomRang2();
        $formHinhFinal = new PhongKhamHinhFinal();
        $formDentalForm = new PhongKhamDentalForm();
        $listChupHinh = $listChupBanhMoi = $listChupCui = $listChupFinal = $listHinhTknc = $listUomRang1 = $listUomRang2 = $listHinhFinal = $listDentalForm = [];
        if (!CONSOLE_HOST) {
            $service = '';
        } else {
            $service = GapiComponent::getService();
        }

        $time = strtotime(date('d-m-Y'));

        $customer = Dep365CustomerOnlineImport::find()->where(['id' => $id])->one();
        if ($customer == null) {
            Yii::$app->session->setFlash('alert', [
                'class' => 'alert-warning',
                'body' => 'Không tìm thấy dữ liệu'
            ]);
            return $this->redirect(['import-customer']);
        }
        /* CHUP HINH */
        $checkChupHinhData = CustomerImages::getListFilesByCustomer($id, Yii::$app->params['chup-hinh-catagory'][ChupHinhController::FOLDER]);
        foreach ($checkChupHinhData as $chuphinh) {
            if (file_exists(Url::to('@backend/web') . '/uploads/customer/' . $customer->slug . '-' . $customer->id . '/' . ChupHinhController::FOLDER . '/' . $chuphinh->image)) {
                $listChupHinh[] = [
                    'type' => 'local',
                    'id' => $chuphinh->id,
                    'name' => $chuphinh->image,
                    'webContentLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . ChupHinhController::FOLDER . '/' . $chuphinh->image,
                    'thumbnailLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . ChupHinhController::FOLDER . '/thumb/' . $chuphinh->image,
                ];
            }
        }
        /*$checkGDriveFolder = PhongKhamChupHinh::find()->where(['between', 'created_at', $time, $time + 86399])->andWhere(['customer_id' => $id])->one();
        if ($checkGDriveFolder == null) {
            $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), self::FOLDER);
            $checkGDriveFolder = new PhongKhamChupHinh();
            $checkGDriveFolder->customer_id = $id;
            $checkGDriveFolder->folder_id = $gDriveFolder;
            $checkGDriveFolder->save();
        } else {
            $getFolder = GapiComponent::getFile($service, $checkGDriveFolder->folder_id);
            if ($getFolder != null) {
                $gDriveFolder = $checkGDriveFolder->folder_id;
            } else {
                $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), self::FOLDER);
                $checkGDriveFolder->folder_id = $gDriveFolder;
                $checkGDriveFolder->save();
            }
        }*/
        if (count($listChupHinh) <= 0) {
            $rowChupHinh = PhongKhamChupHinh::find()->where(['customer_id' => $id])->all();
            if ($rowChupHinh != null) {
                foreach ($rowChupHinh as $chupHinh) {
                    $list = GapiComponent::getListFile($service, $chupHinh->folder_id);
                    if ($list != null && count($list) > 0) {
                        $listChupHinh = array_merge($listChupHinh, $list);
                    }
                }
            }
        }
        /* END CHUP HINH */
        /* CHUP BANH MOI */
        $checkChupBanhMoiData = CustomerImages::getListFilesByCustomer($id, Yii::$app->params['chup-hinh-catagory'][ChupBanhMoiController::FOLDER]);
        foreach ($checkChupBanhMoiData as $chuphinh) {
            if (file_exists(Url::to('@backend/web') . '/uploads/customer/' . $customer->slug . '-' . $customer->id . '/' . ChupBanhMoiController::FOLDER . '/' . $chuphinh->image)) {
                $listChupBanhMoi[] = [
                    'type' => 'local',
                    'id' => $chuphinh->id,
                    'name' => $chuphinh->image,
                    'webContentLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . ChupBanhMoiController::FOLDER . '/' . $chuphinh->image,
                    'thumbnailLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . ChupBanhMoiController::FOLDER . '/thumb/' . $chuphinh->image,
                ];
            }
        }
        /*$checkGDriveFolder = PhongKhamChupBanhMoi::find()->where(['between', 'created_at', $time, $time + 86399])->andWhere(['customer_id' => $id])->one();
        if ($checkGDriveFolder == null) {
            $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), ChupBanhMoiController::FOLDER);
            $checkGDriveFolder = new PhongKhamChupBanhMoi();
            $checkGDriveFolder->customer_id = $id;
            $checkGDriveFolder->folder_id = $gDriveFolder;
            $checkGDriveFolder->save();
        } else {
            $getFolder = GapiComponent::getFile($service, $checkGDriveFolder->folder_id);
            if ($getFolder != null) {
                $gDriveFolder = $checkGDriveFolder->folder_id;
            } else {
                $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), ChupBanhMoiController::FOLDER);
                $checkGDriveFolder->folder_id = $gDriveFolder;
                $checkGDriveFolder->save();
            }
        }*/
        if (count($listChupBanhMoi) <= 0) {
            $rowChupBanhMoi = PhongKhamChupBanhMoi::find()->where(['customer_id' => $id])->all();
            if ($rowChupBanhMoi != null) {
                foreach ($rowChupBanhMoi as $chupBanhMoi) {
                    $list = GapiComponent::getListFile($service, $chupBanhMoi->folder_id);
                    if ($list != null && count($list) > 0) {
                        $listChupBanhMoi = array_merge($listChupBanhMoi, $list);
                    }
                }
            }
        }
        /* END CHUP BANH MOI */
        /* CHUP CUI */
        $checkChupCuiData = CustomerImages::getListFilesByCustomer($id, Yii::$app->params['chup-hinh-catagory'][ChupCuiController::FOLDER]);
        foreach ($checkChupCuiData as $chuphinh) {
            if (file_exists(Url::to('@backend/web') . '/uploads/customer/' . $customer->slug . '-' . $customer->id . '/' . ChupCuiController::FOLDER . '/' . $chuphinh->image)) {
                $listChupCui[] = [
                    'type' => 'local',
                    'id' => $chuphinh->id,
                    'name' => $chuphinh->image,
                    'webContentLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . ChupCuiController::FOLDER . '/' . $chuphinh->image,
                    'thumbnailLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . ChupCuiController::FOLDER . '/thumb/' . $chuphinh->image,
                ];
            }
        }
        /*$checkGDriveFolder = PhongKhamChupCui::find()->where(['between', 'created_at', $time, $time + 86399])->andWhere(['customer_id' => $id])->one();
        if ($checkGDriveFolder == null) {
            $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), ChupCuiController::FOLDER);
            $checkGDriveFolder = new PhongKhamChupCui();
            $checkGDriveFolder->customer_id = $id;
            $checkGDriveFolder->folder_id = $gDriveFolder;
            $checkGDriveFolder->save();
        } else {
            $getFolder = GapiComponent::getFile($service, $checkGDriveFolder->folder_id);
            if ($getFolder != null) {
                $gDriveFolder = $checkGDriveFolder->folder_id;
            } else {
                $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), ChupCuiController::FOLDER);
                $checkGDriveFolder->folder_id = $gDriveFolder;
                $checkGDriveFolder->save();
            }
        }*/
        if (count($listChupCui) <= 0) {
            $rowChupCui = PhongKhamChupCui::find()->where(['customer_id' => $id])->all();
            if ($rowChupCui != null) {
                foreach ($rowChupCui as $chupCui) {
                    $list = GapiComponent::getListFile($service, $chupCui->folder_id);
                    if ($list != null && count($list) > 0) {
                        $listChupCui = array_merge($listChupCui, $list);
                    }
                }
            }
        }
        /* END CHUP CUI */
        /* CHUP KET THUC */
        $checkChupFinalData = CustomerImages::getListFilesByCustomer($id, Yii::$app->params['chup-hinh-catagory'][ChupFinalController::FOLDER]);
        foreach ($checkChupFinalData as $chuphinh) {
            if (file_exists(Url::to('@backend/web') . '/uploads/customer/' . $customer->slug . '-' . $customer->id . '/' . ChupFinalController::FOLDER . '/' . $chuphinh->image)) {
                $listChupFinal[] = [
                    'type' => 'local',
                    'id' => $chuphinh->id,
                    'name' => $chuphinh->image,
                    'webContentLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . ChupFinalController::FOLDER . '/' . $chuphinh->image,
                    'thumbnailLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . ChupFinalController::FOLDER . '/thumb/' . $chuphinh->image,
                ];
            }
        }
        /*$checkGDriveFolder = PhongKhamChupFinal::find()->where(['between', 'created_at', $time, $time + 86399])->andWhere(['customer_id' => $id])->one();
        if ($checkGDriveFolder == null) {
            $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), ChupFinalController::FOLDER);
            $checkGDriveFolder = new PhongKhamChupFinal();
            $checkGDriveFolder->customer_id = $id;
            $checkGDriveFolder->folder_id = $gDriveFolder;
            $checkGDriveFolder->save();
        } else {
            $getFolder = GapiComponent::getFile($service, $checkGDriveFolder->folder_id);
            if ($getFolder != null) {
                $gDriveFolder = $checkGDriveFolder->folder_id;
            } else {
                $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), ChupFinalController::FOLDER);
                $checkGDriveFolder->folder_id = $gDriveFolder;
                $checkGDriveFolder->save();
            }
        }*/
        if (count($listChupFinal) <= 0) {
            $rowChupFinal = PhongKhamChupFinal::find()->where(['customer_id' => $id])->all();
            if ($rowChupFinal != null) {
                foreach ($rowChupFinal as $chupFinal) {
                    $list = GapiComponent::getListFile($service, $chupFinal->folder_id);
                    if ($list != null && count($list) > 0) {
                        $listChupFinal = array_merge($listChupFinal, $list);
                    }
                }
            }
        }
        /* END CHUP KET THUC */
        /* HINH TKNC */
        $checkHinhTkncData = CustomerImages::getListFilesByCustomer($id, Yii::$app->params['chup-hinh-catagory'][TkncController::FOLDER]);
        foreach ($checkHinhTkncData as $chuphinh) {
            if (file_exists(Url::to('@backend/web') . '/uploads/customer/' . $customer->slug . '-' . $customer->id . '/' . TkncController::FOLDER . '/' . $chuphinh->image)) {
                $listHinhTknc[] = [
                    'type' => 'local',
                    'id' => $chuphinh->id,
                    'name' => $chuphinh->image,
                    'webContentLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . TkncController::FOLDER . '/' . $chuphinh->image,
                    'thumbnailLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . TkncController::FOLDER . '/thumb/' . $chuphinh->image,
                    'imageType' => $chuphinh->type
                ];
            }
        }
        /*$checkGDriveFolder = PhongKhamHinhTknc::find()->where(['between', 'created_at', $time, $time + 86399])->andWhere(['customer_id' => $id])->one();
        if ($checkGDriveFolder == null) {
            $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), TkncController::FOLDER);
            $checkGDriveFolder = new PhongKhamHinhTknc();
            $checkGDriveFolder->customer_id = $id;
            $checkGDriveFolder->folder_id = $gDriveFolder;
            $checkGDriveFolder->save();
        } else {
            $getFolder = GapiComponent::getFile($service, $checkGDriveFolder->folder_id);
            if ($getFolder != null) {
                $gDriveFolder = $checkGDriveFolder->folder_id;
            } else {
                $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), TkncController::FOLDER);
                $checkGDriveFolder->folder_id = $gDriveFolder;
                $checkGDriveFolder->save();
            }
        }*/
        if (count($listHinhTknc) <= 0) {
            $rowTknc = PhongKhamHinhTknc::find()->where(['customer_id' => $id])->all();
            if ($rowTknc != null) {
                foreach ($rowTknc as $tknc) {
                    $list = GapiComponent::getListFile($service, $tknc->folder_id);
                    if ($list != null && count($list) > 0) {
                        $listHinhTknc = array_merge($listHinhTknc, $list);
                    }
                }
            }
        }
        /* END HINH TKNC */
        /* UOM RANG 1 */
        $checkUomRang1Data = CustomerImages::getListFilesByCustomer($id, Yii::$app->params['chup-hinh-catagory'][UomRang1Controller::FOLDER]);
        foreach ($checkUomRang1Data as $chuphinh) {
            if (file_exists(Url::to('@backend/web') . '/uploads/customer/' . $customer->slug . '-' . $customer->id . '/' . UomRang1Controller::FOLDER . '/' . $chuphinh->image)) {
                $listUomRang1[] = [
                    'type' => 'local',
                    'id' => $chuphinh->id,
                    'name' => $chuphinh->image,
                    'webContentLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . UomRang1Controller::FOLDER . '/' . $chuphinh->image,
                    'thumbnailLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . UomRang1Controller::FOLDER . '/thumb/' . $chuphinh->image,
                ];
            }
        }
        /*$checkGDriveFolder = PhongKhamUomRang1::find()->where(['between', 'created_at', $time, $time + 86399])->andWhere(['customer_id' => $id])->one();
        if ($checkGDriveFolder == null) {
            $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), UomRang1Controller::FOLDER);
            $checkGDriveFolder = new PhongKhamUomRang1();
            $checkGDriveFolder->customer_id = $id;
            $checkGDriveFolder->folder_id = $gDriveFolder;
            $checkGDriveFolder->save();
        } else {
            $getFolder = GapiComponent::getFile($service, $checkGDriveFolder->folder_id);
            if ($getFolder != null) {
                $gDriveFolder = $checkGDriveFolder->folder_id;
            } else {
                $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), UomRang1Controller::FOLDER);
                $checkGDriveFolder->folder_id = $gDriveFolder;
                $checkGDriveFolder->save();
            }
        }*/
        if (count($listUomRang1) <= 0) {
            $rowUomRang1 = PhongKhamUomRang1::find()->where(['customer_id' => $id])->all();
            if ($rowUomRang1 != null) {
                foreach ($rowUomRang1 as $uomRang1) {
                    $list = GapiComponent::getListFile($service, $uomRang1->folder_id);
                    if ($list != null && count($list) > 0) {
                        $listUomRang1 = array_merge($listUomRang1, $list);
                    }
                }
            }
        }
        /* END UOM RANG 1 */
        /* UOM RANG 2 */
        $checkUomRang2Data = CustomerImages::getListFilesByCustomer($id, Yii::$app->params['chup-hinh-catagory'][UomRang2Controller::FOLDER]);
        foreach ($checkUomRang2Data as $chuphinh) {
            if (file_exists(Url::to('@backend/web') . '/uploads/customer/' . $customer->slug . '-' . $customer->id . '/' . UomRang2Controller::FOLDER . '/' . $chuphinh->image)) {
                $listUomRang2[] = [
                    'type' => 'local',
                    'id' => $chuphinh->id,
                    'name' => $chuphinh->image,
                    'webContentLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . UomRang2Controller::FOLDER . '/' . $chuphinh->image,
                    'thumbnailLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . UomRang2Controller::FOLDER . '/thumb/' . $chuphinh->image,
                ];
            }
        }
        /*$checkGDriveFolder = PhongKhamUomRang2::find()->where(['between', 'created_at', $time, $time + 86399])->andWhere(['customer_id' => $id])->one();
        if ($checkGDriveFolder == null) {
            $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), UomRang2Controller::FOLDER);
            $checkGDriveFolder = new PhongKhamUomRang2();
            $checkGDriveFolder->customer_id = $id;
            $checkGDriveFolder->folder_id = $gDriveFolder;
            $checkGDriveFolder->save();
        } else {
            $getFolder = GapiComponent::getFile($service, $checkGDriveFolder->folder_id);
            if ($getFolder != null) {
                $gDriveFolder = $checkGDriveFolder->folder_id;
            } else {
                $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), UomRang2Controller::FOLDER);
                $checkGDriveFolder->folder_id = $gDriveFolder;
                $checkGDriveFolder->save();
            }
        }*/
        if (count($listUomRang2) <= 0) {
            $rowUomRang2 = PhongKhamUomRang2::find()->where(['customer_id' => $id])->all();
            if ($rowUomRang2 != null) {
                foreach ($rowUomRang2 as $uomRang2) {
                    $list = GapiComponent::getListFile($service, $uomRang2->folder_id);
                    if ($list != null && count($list) > 0) {
                        $listUomRang2 = array_merge($listUomRang2, $list);
                    }
                }
            }
        }
        /* END UOM RANG 2 */
        /* HINH FINAL */
        $checkHinhFinalData = CustomerImages::getListFilesByCustomer($id, Yii::$app->params['chup-hinh-catagory'][HinhFinalController::FOLDER]);
        foreach ($checkHinhFinalData as $chuphinh) {
            if (file_exists(Url::to('@backend/web') . '/uploads/customer/' . $customer->slug . '-' . $customer->id . '/' . HinhFinalController::FOLDER . '/' . $chuphinh->image)) {
                $listHinhFinal[] = [
                    'type' => 'local',
                    'id' => $chuphinh->id,
                    'name' => $chuphinh->image,
                    'webContentLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . HinhFinalController::FOLDER . '/' . $chuphinh->image,
                    'thumbnailLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . HinhFinalController::FOLDER . '/thumb/' . $chuphinh->image,
                ];
            }
        }
        /*$checkGDriveFolder = PhongKhamHinhFinal::find()->where(['between', 'created_at', $time, $time + 86399])->andWhere(['customer_id' => $id])->one();
        if ($checkGDriveFolder == null) {
            $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), HinhFinalController::FOLDER);
            $checkGDriveFolder = new PhongKhamHinhFinal();
            $checkGDriveFolder->customer_id = $id;
            $checkGDriveFolder->folder_id = $gDriveFolder;
            $checkGDriveFolder->save();
        } else {
            $getFolder = GapiComponent::getFile($service, $checkGDriveFolder->folder_id);
            if ($getFolder != null) {
                $gDriveFolder = $checkGDriveFolder->folder_id;
            } else {
                $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), HinhFinalController::FOLDER);
                $checkGDriveFolder->folder_id = $gDriveFolder;
                $checkGDriveFolder->save();
            }
        }*/
        if (count($listHinhFinal) <= 0) {
            $rowHinhFinal = PhongKhamHinhFinal::find()->where(['customer_id' => $id])->all();
            if ($rowHinhFinal != null) {
                foreach ($rowHinhFinal as $hinhFinal) {
                    $list = GapiComponent::getListFile($service, $hinhFinal->folder_id);
                    if ($list != null && count($list) > 0) {
                        $listHinhFinal = array_merge($listHinhFinal, $list);
                    }
                }
            }
        }
        /* END HINH FINAL */
        /* DENTAL FORM */
        $checkDentalForm = CustomerImages::getListFilesByCustomer($id, Yii::$app->params['chup-hinh-catagory'][DentalFormController::FOLDER]);
        foreach ($checkDentalForm as $dentalForm) {
            if (file_exists(Url::to('@backend/web') . '/uploads/customer/' . $customer->slug . '-' . $customer->id . '/' . DentalFormController::FOLDER . '/' . $dentalForm->image)) {
                $listDentalForm[] = [
                    'type' => 'local',
                    'id' => $dentalForm->id,
                    'name' => $dentalForm->image,
                    'webContentLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . DentalFormController::FOLDER . '/' . $dentalForm->image,
                    'thumbnailLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . DentalFormController::FOLDER . '/thumb/' . $dentalForm->image,
                    'imageType' => $dentalForm->type
                ];
            }
        }
        /*$checkGDriveFolder = PhongKhamDentalForm::find()->where(['between', 'created_at', $time, $time + 86399])->andWhere(['customer_id' => $id])->one();
        if ($checkGDriveFolder == null) {
            $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), DentalFormController::FOLDER);
            $checkGDriveFolder = new PhongKhamDentalForm();
            $checkGDriveFolder->customer_id = $id;
            $checkGDriveFolder->folder_id = $gDriveFolder;
            $checkGDriveFolder->save();
        } else {
            $getFolder = GapiComponent::getFile($service, $checkGDriveFolder->folder_id);
            if ($getFolder != null) {
                $gDriveFolder = $checkGDriveFolder->folder_id;
            } else {
                $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), DentalFormController::FOLDER);
                $checkGDriveFolder->folder_id = $gDriveFolder;
                $checkGDriveFolder->save();
            }
        }*/
        if (count($listDentalForm) <= 0) {
            $rowDentalForm = PhongKhamDentalForm::find()->where(['customer_id' => $id])->all();
            if ($rowDentalForm != null) {
                foreach ($rowDentalForm as $dentalForm) {
                    $list = GapiComponent::getListFile($service, $dentalForm->folder_id);
                    if ($list != null && count($list) > 0) {
                        $listDentalForm = array_merge($listDentalForm, $list);
                    }
                }
            }
        }
        /* END DENTAL FORM */
        return $this->render('upload', [
            'id' => $id,
            'customer' => $customer,
            'formAvatar' => $formAvatar,
            'formChupHinh' => $formChupHinh,
            'formChupBanhMoi' => $formChupBanhMoi,
            'formChupCui' => $formChupCui,
            'formChupFinal' => $formChupFinal,
            'formHinhTknc' => $formHinhTknc,
            'formUomRang1' => $formUomRang1,
            'formUomRang2' => $formUomRang2,
            'formHinhFinal' => $formHinhFinal,
            'formDentalForm' => $formDentalForm,
            'listChupHinh' => $listChupHinh,
            'listChupBanhMoi' => $listChupBanhMoi,
            'listChupCui' => $listChupCui,
            'listChupFinal' => $listChupFinal,
            'listHinhTknc' => $listHinhTknc,
            'listUomRang1' => $listUomRang1,
            'listUomRang2' => $listUomRang2,
            'listHinhFinal' => $listHinhFinal,
            'listDentalForm' => $listDentalForm,
        ]);
    }

    public function actionUploadBk($id)
    {
        $customer = Clinic::find()->where(['id' => $id])->one();
        if ($customer === null) {
            return $this->redirect(Url::toRoute('index'));
        }
        if ($customer->full_name == null) {
            Yii::$app->session->setFlash('alert', [
                'body' => 'Vui lòng cập nhật Họ và Tên đầy đủ của khách hàng!',
                'class' => 'alert-warning'
            ]);
            return $this->redirect(Url::toRoute('index'));
        }

        $listFile = [];

        $model = new FormChupHinh();
        $modelAvatar = new FormAvatarCustomer();
        $model->id = $id;
        $modelAvatar->id = $id;

        $checkLocalData = CustomerImages::getListFilesByCustomer($id, Yii::$app->params['chup-hinh-catagory'][self::FOLDER]);
        foreach ($checkLocalData as $chuphinh) {
            if (file_exists(Url::to('@backend/web') . '/uploads/customer/' . $customer->slug . '-' . $customer->id . '/' . self::FOLDER . '/' . $chuphinh->image)) {
                $listFile[] = [
                    'type' => 'local',
                    'id' => $chuphinh->id,
                    'name' => $chuphinh->image,
                    'webContentLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . self::FOLDER . '/' . $chuphinh->image,
                    'thumbnailLink' => Url::to('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . self::FOLDER . '/thumb/' . $chuphinh->image,
                ];
            }
        }
        if (count($listFile) <= 0) {
            $service = GapiComponent::getService();

            $time = strtotime(date('d-m-Y'));
            $checkGDriveFolder = PhongKhamChupHinh::find()->where(['between', 'created_at', $time, $time + 86399])->andWhere(['customer_id' => $id])->one();
            if ($checkGDriveFolder == null) {
                $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), self::FOLDER);
                $checkGDriveFolder = new PhongKhamChupHinh();
                $checkGDriveFolder->customer_id = $id;
                $checkGDriveFolder->folder_id = $gDriveFolder;
                $checkGDriveFolder->save();
            } else {
                $getFolder = GapiComponent::getFile($service, $checkGDriveFolder->folder_id);
                if ($getFolder != null) {
                    $gDriveFolder = $checkGDriveFolder->folder_id;
                } else {
                    $gDriveFolder = GapiComponent::initSubFolderForCustomerByDate($service, MyHelper::createAlias($customer->full_name) . '-' . $id, date('d-m-Y'), self::FOLDER);
                    $checkGDriveFolder->folder_id = $gDriveFolder;
                    $checkGDriveFolder->save();
                }
            }

            $rowChupHinh = PhongKhamChupHinh::find()->where(['customer_id' => $id])->all();
            if ($rowChupHinh != null) {
                foreach ($rowChupHinh as $chuphinh) {
                    $list = GapiComponent::getListFile($service, $chuphinh->folder_id);
                    if ($list != null && count($list) > 0) {
                        $listFile = array_merge($listFile, $list);
                    }
                }
            }
        }

        return $this->render('upload', [
            'customer' => $customer,
            'model' => $model,
            'modelAvatar' => $modelAvatar,
            'listFile' => $listFile,
        ]);
    }

    public function actionUploadImage($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $customer = Clinic::find()->where(['id' => $id])->one();
        if ($customer == null) {
            return [
                'code' => 400,
                'msg' => 'Không tìm thấy khách hàng!'
            ];
        }
        $service = GapiComponent::getService();
        $time = strtotime(date('d-m-Y'));
        /*$checkGDriveFolder = PhongKhamChupHinh::find()->where(['between', 'created_at', $time, $time + 86399])->andWhere(['customer_id' => $id])->one();
        if ($checkGDriveFolder == null) {
            return [
                'code' => 403,
                'data' => [
                    'msg' => 'Khởi tạo Google Drive thất bại!',
                ]
            ];
        }*/
        $code = 200;
        $msg = '';
        $dataImage = [];
        if (Yii::$app->request->isAjax) {
            $model = new FormChupHinh();
            $transaction = Yii::$app->db->beginTransaction(
                Transaction::SERIALIZABLE
            );
            if ($model->load(Yii::$app->request->post())) {
                $file = UploadedFile::getInstances($model, 'fileImage');
                $model->fileImage = $file;
                if ($model->validate()) {
//                    $gDriveFolder = $checkGDriveFolder->folder_id;
                    $data = [];

                    $fileName = $file[0]->baseName . '.' . $file[0]->extension;
                    if ($file[0]->saveAs(Yii::getAlias('@backend/web') . '/uploads/tmp/' . $fileName)) {
                        $msg = 'Upload thành công!';
                        $urlFile = Yii::$app->basePath . '/web/uploads/tmp/' . $fileName;
//                        /* 21-02-2020: Đóng code lưu hình trên server vì server đầy */
                        $image = $this->createImage('@backend/web', $urlFile, 220, 220, '/uploads/customer/' . $customer->slug . '-' . $customer->id . '/' . self::FOLDER . '/thumb/', null);
                        $this->createImage('@backend/web', $urlFile, null, null, '/uploads/customer/' . $customer->slug . '-' . $customer->id . '/' . self::FOLDER . '/', $image);

//                        $idImage = GapiComponent::uploadImageToDrive($service, $fileName, '@backend/web/uploads/tmp', $gDriveFolder);
//                        if ($idImage == null) {
//                            $code = 403;
//                            $msg = "Lưu hình lên drive thất bại!";
//                        } else {
                            $this->deleteImage('@backend/web', '/uploads/tmp/', $fileName);

                            $customerImage = new CustomerImages();
                            $customerImage->customer_id = $customer->id;
                            $customerImage->catagory_id = Yii::$app->params['chup-hinh-catagory'][self::FOLDER];
//                            $customerImage->image = $fileName;
//                            /* 21-02-2020: lưu image là url file tmp */
                            $customerImage->image = $image;
//                            $customerImage->google_id = $idImage;
                            if (!$customerImage->save()) {
                                $code = 400;
                                $msg = "Lưu hình thất bại!";
                                $data = [
                                    $customerImage->getErrors(),
                                    $customerImage->getAttributes()
                                ];
                                $transaction->rollBack();
                            } else {
                                $transaction->commit();
//                                $file = GapiComponent::getFile($service, $idImage);
                                $data = [
                                    'type' => 'local',
                                    'id' => $customerImage->getPrimaryKey(),
                                    'title' => $fileName,
//                                    /* 21-02-2020: show file từ google drive chứ ko show từ server nữa */
                                    'image' => Yii::getAlias('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . self::FOLDER . '/' . $image,
                                    'thumb' => Yii::getAlias('@web/uploads') . '/customer/' . $customer->slug . '-' . $customer->id . '/' . self::FOLDER . '/thumb/' . $image,
//                                    'image' => $file['webContentLink'],
//                                    'thumb' => $file['thumbnailLink'],
                                ];
                            }
//                        }
                    }
                    $dataImage = $data;
                } else {
                    $code = 400;
                    $msg = $model->getErrors('fileImage');
                }
            } else {
                $code = 400;
                $msg = 'Lỗi xử lý dữ liệu!';
            }
        } else {
            $code = 400;
            $msg = 'Yêu cầu không hợp lệ!';
        }
        return [
            'code' => $code,
            'data' => [
                'msg' => $msg,
                'dataImage' => $dataImage,
            ],
        ];
    }

    public function actionReload()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $code = 200;
        $msg = '';
        $data = [];
        $id = Yii::$app->request->post('id');
        $service = GapiComponent::getService();
        $file = GapiComponent::getFile($service, $id);
        if ($file == null) {
            $code = 403;
            $msg = "Có lỗi khi làm mới!";
        } else {
            $data = [
                'id' => $file['id'],
                'title' => $file['name'],
                'image' => $file['webContentLink'],
                'thumb' => $file['thumbnailLink'],
            ];
        }
        return [
            'code' => $code,
            'data' => [
                'msg' => $msg,
                'dataImage' => $data
            ]
        ];
    }

    public function actionUploadAvatar($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (!Yii::$app->request->isAjax) {
            return [
            'code' => 400,
            'msg' => 'Yêu cầu không hợp lệ'
        ];
        }
        $model = new FormAvatarCustomer();
        if (!$model->load(Yii::$app->request->post())) {
            return [
            'code' => 400,
            'msg' => 'Lỗi xử ly dữ liệu!'
        ];
        }
        if (!$model->validate()) {
            return [
            'code' => 400,
            'msg' => 'Lỗi kiểm tra dữ liệu!'
        ];
        }
        $file = UploadedFile::getInstance($model, 'fileImage');
        $img = $file->baseName . '.' . $file->extension;
        $file->saveAs('uploads/tmp/' . $img);
        $urlImage = Yii::$app->basePath . '/web/uploads/tmp/' . $img;
        $customer = $this->findModel($model->id);
        $avatarOld = $customer->avatar;
        $customer->avatar = $this->createImage('@backend/web', $urlImage, 70, 70, '/uploads/avatar/70x70/');
        $this->createImage('@backend/web', $urlImage, 200, 200, '/uploads/avatar/200x200/', $customer->avatar);
        $this->deleteImage('@backend/web', '/uploads/tmp/', $img);
        if ($customer->save()) {
            $this->deleteImage('@backend/web', '/uploads/avatar/70x70/', $avatarOld);
            $this->deleteImage('@backend/web', '/uploads/avatar/200x200/', $avatarOld);
            return [
                'code' => 200,
                'msg' => "Cập nhật avatar thành công",
                'id' => $customer->primaryKey
            ];
        } else {
            return [
                'code' => 501,
                'msg' => 'Cập nhật avatar thất bại!'
            ];
        }
    }

    public function actionAppNotif($user_id, $customer_id)
    {
        if (CONSOLE_HOST == false/*\Yii::$app->request->getUserIP() == '127.0.0.1'*/) {
            $client = new Client([
                'verify' => Url::to('@backend/modules/clinic/token/cacert.pem')
            ]);
        } else {
            $client = new Client();
        }
        $client->request('GET', 'https://api.myauris.vn/api/PushNotification?user_id=' . $user_id . '&customer_id=' . $customer_id, ['verify' => false]);
    }

    protected function findModel($id)
    {
        $model = \backend\models\Customer::findOne($id);
        if (($model !== null)) {
            return $model;
        }

        return false;
    }
}
