<?php

namespace backend\modules\clinic\controllers;

use Yii;
use backend\modules\clinic\models\PhongKhamKhuyenMai;
use backend\modules\clinic\models\search\PhongKhamKhuyenMaiSearch;
use backend\components\MyController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\components\MyComponent;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * PhongKhamKhuyenMaiController implements the CRUD actions for PhongKhamKhuyenMai model.
 */
class PhongKhamKhuyenMaiController extends MyController
{
    public function init()
    {
        $cache = Yii::$app->cache;
        $key = 'get-list-khuyen-mai';
        $cache->delete($key);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchModel = new PhongKhamKhuyenMaiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if (MyComponent::hasCookies('pageSize')) {
            $dataProvider->pagination->pageSize = MyComponent::getCookies('pageSize');
        } else {
            $dataProvider->pagination->pageSize = 10;
        }

        $pageSize = $dataProvider->pagination->pageSize;

        $totalCount = $dataProvider->totalCount;

        $totalPage = (($totalCount + $pageSize - 1) / $pageSize);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'totalPage' => $totalPage,
        ]);
    }

    public function actionPerpage($perpage)
    {
        MyComponent::setCookies('pageSize', $perpage);
    }

    public function actionView($id)
    {
        if ($this->findModel($id)) {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        } else {
            return $this->redirect(['index']);
        }
    }

    public function actionCreate()
    {
        if (Yii::$app->request->isAjax) {
            $model = new PhongKhamKhuyenMai();

            /*if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                try {
                    $model->save();
                    Yii::$app->session->setFlash('alert', [
                        'body' => Yii::$app->params['create-success'],
                        'class' => 'bg-success',
                    ]);
                } catch (\yii\db\Exception $exception) {
                    Yii::$app->session->setFlash('alert', [
                        'body' => Yii::$app->params['create-danger'],
                        'class' => 'bg-danger',
                    ]);
                }
                return $this->refresh();
            }*/

            return $this->renderAjax('form-ajax', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($id)
    {
        if (Yii::$app->request->isAjax) {
            $model = $this->findModel($id);

            /*if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                try {
                    $model->save();
                    Yii::$app->session->setFlash('alert', [
                        'body' => Yii::$app->params['update-success'],
                        'class' => 'bg-success',
                    ]);
                } catch (\yii\db\Exception $exception) {
                    Yii::$app->session->setFlash('alert', [
                        'body' => $exception->getMessage(),
                        'class' => 'bg-danger',
                    ]);
                }
                return $this->refresh();
            }*/

            return $this->renderAjax('form-ajax', [
                'model' => $model,
            ]);
        }
    }

    public function actionValidateKhuyenMai($id = null)
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $model = new PhongKhamKhuyenMai();
            if ($id != null) {
                $model = PhongKhamKhuyenMai::find()->where(['id' => $id])->one();
            }
            if ($model->load(Yii::$app->request->post())) {
                return ActiveForm::validate($model);
            }
        }
    }

    public function actionSubmitKhuyenMai($id = null)
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $model = new PhongKhamKhuyenMai();
            if ($id != null) {
                $model = PhongKhamKhuyenMai::find()->where(['id' => $id])->one();
            }
            if ($model == null) {
                return [
                'code' => 404,
                'msg' => 'Không tìm thấy dữ liệu'
            ];
            }
            if (!$model->load(Yii::$app->request->post()) || !$model->validate() || !$model->save()) {
                return [
                'code' => 400,
                'msg' => $id == null ? Yii::$app->params['create-danger'] : Yii::$app->params['update-danger'],
                'error' => $model->getErrors()
            ];
            }
            return [
                'code' => 200,
                'msg' => $id == null ? Yii::$app->params['create-success'] : Yii::$app->params['update-success']
            ];
        }
    }

    public function actionDelete()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
            $id = Yii::$app->request->post('id');
            try {
                if ($this->findModel($id)->delete()) {
                    return [
                        "status" => "success"
                    ];
                } else {
                    return [
                        "status" => "failure"
                    ];
                }
            } catch (\yii\db\Exception $e) {
                return [
                    "status" => "exception"
                ];
            }
        }

        return $this->redirect(['index']);
    }

    public function actionShowHide()
    {
        if (Yii::$app->request->isAjax) {
            $id = Yii::$app->request->post('id');

            $model = $this->findModel($id);
            try {
                if ($model->status == 1) {
                    $model->status = 0;
                } else {
                    $model->status = 1;
                }
                if ($model->save()) {
                    echo 1;
                }
            } catch (\yii\db\Exception $exception) {
                echo 0;
            }
        }
    }

    public function actionDeleteMultiple()
    {
        try {
            $action = Yii::$app->request->post('action');
            $selectCheckbox = Yii::$app->request->post('selection');
            if ($action === 'c') {
                if ($selectCheckbox) {
                    foreach ($selectCheckbox as $id) {
                        $this->findModel($id)->delete();
                    }
                    \Yii::$app->session->setFlash('indexFlash', 'Bạn đã xóa thành công.');
                }
            }
        } catch (\yii\db\Exception $e) {
            if ($e->errorInfo[1] == 1451) {
                throw new \yii\web\HttpException(400, 'Failed to delete the object.');
            } else {
                throw $e;
            }
        }
        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = PhongKhamKhuyenMai::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionGetPriceKhuyenMai()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $id = Yii::$app->request->post('id');
            $khuyenmai = PhongKhamKhuyenMai::find()->where(['id' => $id])->one();
            if ($khuyenmai == null) {
                return [
                'code' => 404,
                'msg' => 'Không tìm thấy khuyến mãi'
            ];
            }
            return [
                'code' => 200,
                'price' => $khuyenmai->price,
                'type' => $khuyenmai->type
            ];
        }
    }
}
